version: '3'

networks:
  http_network:
    external: true
  int:
    external: false

services:
  db:
    image: mysql:5.7
    restart: always
    networks:
      - int
    environment:
      MYSQL_ROOT_PASSWORD: supersecretrootpassword
      MYSQL_USER: main
      MYSQL_DATABASE: scrabble
      MYSQL_PASSWORD: supersecretmainpassword
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
  web:
    build: .
    restart: always
    networks:
      - int
      - http_network
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:1.ctf.makerforce.io"
      - "traefik.port=80"
      - "traefik.docker.network=http_network"


# vim: noai:ts=2:sw=2
