version: '3'

networks:
  http_network:
    external: true

services:
  web:
    build: .
    restart: always
    networks:
      - http_network
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:5.ctf.makerforce.io"
      - "traefik.port=80"
      - "traefik.docker.network=http_network"


# vim: noai:ts=2:sw=2
